policies:
  - type: commit
    spec:
      headerLength: 89
      dco: false
      gpg: false
      imperative: true
      maximumOfOneCommit: true
      requireCommitBody: false
      conventional:
        types:
          - "build"
          - "chore"
          - "ci"
          - "docs"
          - "perf"
          - "refactor"
          - "style"
          - "test"
          - "type"
        scopes:
          - "example"
          - "api"
  - type: license
    spec:
      skipPaths:
        - .git/
        - .build*/
      includeSuffixes:
        - .ext
      excludeSuffixes:
        - .exclude-ext-prefix.ext
      header: |
        This is the contents of a license header.
